server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      routes:
        - id: patient-service
          uri: http://patient-service:8080
          predicates:
            - Path=/patients/**
        - id: notes-service
          uri: http://notes-service:8080
          predicates:
            - Path=/notes/**
        - id: risk-service
          uri: http://risk-service:8080
          predicates:
            - Path=/risk/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/ui/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
